### ISSUE TITLE
Dedicated RG for ACR to support alternate lifecycle 

### ISSUE THREAD

**Issue by manoatsas** [sassoftware/viya4-iac-azure#132]
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-best-practices#dedicated-resource-group

ACR can be shared across various Viya 4 deployments. Also ACR lifecycle can be longer compared to rest of the resources to reduce cloud costs.

**Comment by NormJohnIV** [comment]
I disagree. The document talks about a user wanting to test out many ways to use the container registry an thus put it in it own rg. We are not doing that. We can already use the existing ACR setup for multiple viya deployments on the same cluster or in clusters existing in the same rg. Furthermore, with our IaC code this seems like an anti pattern. Who would control the ACR since only one deployment would have it? What happens it they want to take down that infrastructure but others are using the acr? If users want to have cross rg ACR I think that should be done outside of this tooling and they just tell viya about it. That is already supported.

**Comment by manoatsas** [comment]
I'd keep the discussion here for input from the field where more realistic use cases would arise. Primary use case is not necessarily shared ACR but to account for lifecycle differences between AKS and ACR. ACR may be once per release of Viya4 whereas AKS and other components would have shorter lifecycles (e.g., weekends, nightly or other cycles) to reduce cloud costs.
